import house1 from '../../assets/houses/1.jpeg';
import house10 from '../../assets/houses/10.jpeg';
import house2 from '../../assets/houses/2.jpeg';
import house3 from '../../assets/houses/3.jpeg';
import house4 from '../../assets/houses/4.jpeg';
import house5 from '../../assets/houses/5.jpeg';
import house6 from '../../assets/houses/6.jpeg';
import house7 from '../../assets/houses/7.jpeg';
import house8 from '../../assets/houses/8.jpeg';
import house9 from '../../assets/houses/9.jpeg';

const parsePrice = (price: string) => {
  return parseFloat(price.replace(/[^\d.-]/g, '')) || 0;
};

export const properties = [
    {
        id: 1,
        title: "Luxury Villa",
        price: "160,000,000",
        size: "846 m² (9103 sqft)",
        location: "Yufuin-cho, Oita",
        imageUrl: house1,
        rating: 4.1,
        beds: 4,
    },
    {
        id: 2,
        title: "Modern Apt",
        price: "100,000,000",
        size: "165 m² (1779 sqft)",
        location: "Kamimeguro, Tokyo",
        imageUrl: house2,
        rating: 3.9,
        beds: 3,
    },
    {
        id: 3,
        title: "Luxury Villar",
        price: "600,000,000",
        size: "120 m² (1292 sqft)",
        location: "Kamimeguro, Tokyo",
        imageUrl: house3,
        rating: 4.5,
        beds: 5,
    },
    {
        id: 4,
        title: "Modern Apt",
        price: "350,000,000",
        size: "1522 m² (16384 sqft)",
        location: "Yufuin-cho, Oita",
        imageUrl: house4,
        rating: 4.2,
        beds: 4,
    },
    {
        id: 5,
        title: "Luxury Villa",
        price: "79,400,000",
        size: "45 m² (484 sqft)", 
        location: "Ochiai, Tama-shi",
        imageUrl: house5,
        rating: 3.8,
        beds: 2,
    },
    {
        id: 6,
        title: "Luxury Apt",
        price: "300,000,000",
        size: "120 m² (1292 sqft)", 
        location: "Kamimeguro, Tokyo",
        imageUrl: house6,
        rating: 4.3,
        beds: 4,
    },
    {
        id: 7,
        title: "Luxury Villa",
        price: "250,000,000",
        size: "80 m² (861 sqft)", 
        location: "Higashiyama, Kyoto",
        imageUrl: house7,
        rating: 3.9,
        beds: 3,
    },
    {
        id: 8,
        title: "Modern Villa",
        price: "450,000,000",
        size: "200 m² (2152 sqft)", 
        location: "Namba, Osaka",
        imageUrl: house8,
        rating: 4.0,
        beds: 5,
    },
    {
        id: 9,
        title: "Penthouse",
        price: "800,000,000",
        size: "300 m² (3229 sqft)", 
        location: "Tokyo, Hokkaido",
        imageUrl: house9,
        rating: 4.6,
        beds: 6,
    },
    {
        id: 10,
        title: "Modern Villa",
        price: "500,000,000",
        size: "500 m² (5382 sqft)", 
        location: "Shibuya, Tokyo",
        imageUrl: house10,
        rating: 4.2,
        beds: 6,
    },
    {
        id: 11,
        title: "Luxury Villa",
        price: "160,000,000",
        size: "846 m² (9103 sqft)",
        location: "Yufuin-cho, Oita",
        imageUrl: house1,
        rating: 4.1,
        beds: 4,
    },
    {
        id: 12,
        title: "Modern Apt",
        price: "100,000,000",
        size: "165 m² (1779 sqft)",
        location: "Kamimeguro, Tokyo",
        imageUrl: house2,
        rating: 3.9,
        beds: 3,
    },
    {
        id: 13,
        title: "Luxury Villar",
        price: "600,000,000",
        size: "120 m² (1292 sqft)",
        location: "Kamimeguro, Tokyo",
        imageUrl: house3,
        rating: 4.5,
        beds: 5,
    },
    {
        id: 14,
        title: "Modern Apt",
        price: "350,000,000",
        size: "1522 m² (16384 sqft)",
        location: "Yufuin-cho, Oita",
        imageUrl: house4,
        rating: 4.2,
        beds: 4,
    },
    {
        id: 15,
        title: "Luxury Villa",
        price: "79,400,000",
        size: "45 m² (484 sqft)", 
        location: "Ochiai, Tama-shi",
        imageUrl: house5,
        rating: 3.8,
        beds: 2,
    },
    {
        id: 16,
        title: "Luxury Apt",
        price: "300,000,000",
        size: "120 m² (1292 sqft)", 
        location: "Kamimeguro, Tokyo",
        imageUrl: house6,
        rating: 4.3,
        beds: 4,
    },
    {
        id: 17,
        title: "Luxury Villa",
        price: "250,000,000",
        size: "80 m² (861 sqft)", 
        location: "Higashiyama, Kyoto",
        imageUrl: house7,
        rating: 3.9,
        beds: 3,
    },
    {
        id: 18,
        title: "Modern Villa",
        price: "450,000,000",
        size: "200 m² (2152 sqft)", 
        location: "Namba, Osaka",
        imageUrl: house8,
        rating: 4.0,
        beds: 5,
    },
    {
        id: 19,
        title: "Penthouse",
        price: "800,000,000",
        size: "300 m² (3229 sqft)", 
        location: "Tokyo, Hokkaido",
        imageUrl: house9,
        rating: 4.6,
        beds: 6,
    },
    {
        id: 20,
        title: "Modern Villa",
        price: "500,000,000",
        size: "500 m² (5382 sqft)", 
        location: "Shibuya, Tokyo",
        imageUrl: house10,
        rating: 4.2,
        beds: 6,
    },
    {
        id: 21,
        title: "Modern Villa",
        price: "500,000,000",
        size: "500 m² (5382 sqft)", 
        location: "Shibuya, Tokyo",
        imageUrl: house10,
        rating: 4.2,
        beds: 6,
    },
    {
        id: 21,
        title: "Luxury Villa",
        price: "160,000,000",
        size: "846 m² (9103 sqft)",
        location: "Yufuin-cho, Oita",
        imageUrl: house1,
        rating: 4.1,
        beds: 4,
    },
    {
        id: 22,
        title: "Modern Apt",
        price: "100,000,000",
        size: "165 m² (1779 sqft)",
        location: "Kamimeguro, Tokyo",
        imageUrl: house2,
        rating: 3.9,
        beds: 3,
    },
    {
        id: 23,
        title: "Luxury Villar",
        price: "600,000,000",
        size: "120 m² (1292 sqft)",
        location: "Kamimeguro, Tokyo",
        imageUrl: house3,
        rating: 4.5,
        beds: 5,
    },
    {
        id: 24,
        title: "Modern Apt",
        price: "350,000,000",
        size: "1522 m² (16384 sqft)",
        location: "Yufuin-cho, Oita",
        imageUrl: house4,
        rating: 4.2,
        beds: 4,
    },
    {
        id: 25,
        title: "Luxury Villa",
        price: "79,400,000",
        size: "45 m² (484 sqft)", 
        location: "Ochiai, Tama-shi",
        imageUrl: house5,
        rating: 3.8,
        beds: 2,
    },
    {
        id: 26,
        title: "Luxury Apt",
        price: "300,000,000",
        size: "120 m² (1292 sqft)", 
        location: "Kamimeguro, Tokyo",
        imageUrl: house6,
        rating: 4.3,
        beds: 4,
    },
    {
        id: 27,
        title: "Luxury Villa",
        price: "250,000,000",
        size: "80 m² (861 sqft)", 
        location: "Higashiyama, Kyoto",
        imageUrl: house7,
        rating: 3.9,
        beds: 3,
    },
    {
        id: 28,
        title: "Modern Villa",
        price: "450,000,000",
        size: "200 m² (2152 sqft)", 
        location: "Namba, Osaka",
        imageUrl: house8,
        rating: 4.0,
        beds: 5,
    },
    {
        id: 29,
        title: "Penthouse",
        price: "800,000,000",
        size: "300 m² (3229 sqft)", 
        location: "Tokyo, Hokkaido",
        imageUrl: house9,
        rating: 4.6,
        beds: 6,
    },
    {
        id: 30,
        title: "Modern Villa",
        price: "500,000,000",
        size: "500 m² (5382 sqft)", 
        location: "Shibuya, Tokyo",
        imageUrl: house10,
        rating: 4.2,
        beds: 6,
    },
].map(property => ({
    ...property,
    id: property.id.toString(),
    price: parsePrice(property.price),
}));
